"""
conf.py overrides for testing Admonitions feature.
"""

doxtr_admonitions = {
    'generic': {
        'before_skip': '1.5em plus 0.5em minus 0.5em',
        'after_skip': '1.2em plus 0.5em minus 0.5em',
    },
    'note': {
        'title_background_color': '#0B5ED7',
        'title_icon_box_background_color': '#0B5ED7',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#E8F0FE',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
        'title_icon': r'\textbf{i}',
    },
    'warning': {
        'title_background_color': '#FF0000',
        'title_icon_box_background_color': '#FF0000',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#FFE8E8',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'hint': {
        'title_background_color': '#0092FA',
        'title_icon_box_background_color': '#0092FA',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#E8F4FD',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'danger': {
        'title_background_color': '#D32F2F',
        'title_icon_box_background_color': '#D32F2F',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#FFEBEE',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'error': {
        'title_background_color': '#B71C1C',
        'title_icon_box_background_color': '#B71C1C',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#FFCDD2',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'caution': {
        'title_background_color': '#FFA000',
        'title_icon_box_background_color': '#FFFFFF',
        'title_font_color': '#000000',
        'content_background_color': '#FFF8E1',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'tip': {
        'title_background_color': '#008734',
        'title_icon_box_background_color': '#008734',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#E8F5E9',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'important': {
        'title_background_color': '#6A1B9A',
        'title_icon_box_background_color': '#6A1B9A',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#F3E5F5',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'attention': {
        'title_background_color': '#E65100',
        'title_icon_box_background_color': '#E65100',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#FFF3E0',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
    'seealso': {
        'style': 'default',
        'title_icon': r'\textbf{S}',
        'title_background_color': '#0B5ED7',
        'title_icon_box_background_color': '#0B5ED7',
        'title_font_color': '#FFFFFF',
        'title_icon_color': '#FFFFFF',
        'content_background_color': '#E8F0FE',
        'content_background_color_nested': '#FFFFFF',
        'content_font_color': '#000000',
    },
}
